import "../globals.css";
import {Karla} from "next/font/google";
import Footer from "./components/footer";
import Nav2 from "./components/nav_advanced";
// import {Provider} from "./context/AuthContext";
import {ToastContainer, toast} from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Head from "next/head";

const font = Karla({
  subsets: ["latin", "latin-ext"],
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata = {
    title: "Dike Wisdom - Homepage", description: "Generated by create next app", icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({ children, }:{ children: React.ReactNode}) {    
    

    return (
      <html lang="en">
        <body className={`${font.className} flex  flex-col min-h-screen`}>
          {/* <Provider> */}
          <Nav2 />
          <main>
            <ToastContainer className="custom-toast" />
            {children}
          </main>
          <Footer />
          {/* </Provider> */}
        </body>
      </html>
    );
}
